export const PIECE_LIST = [
    {
        id: 1,
        color: "red",
        shape: "circle",
        number: 1,
        language: "math",
        display: "1",
    },
    {
        id: 2,
        color: "red",
        shape: "circle",
        number: 2,
        language: "math",
        display: "2",
    },
    {
        id: 3,
        color: "red",
        shape: "circle",
        number: 1,
        language: "japanese",
        display: "一",
    },
    {
        id: 4,
        color: "red",
        shape: "circle",
        number: 2,
        language: "japanese",
        display: "二",
    },
    {
        id: 5,
        color: "red",
        shape: "square",
        number: 1,
        language: "math",
        display: "1",
    },
    {
        id: 6,
        color: "red",
        shape: "square",
        number: 2,
        language: "math",
        display: "2",
    },
    {
        id: 7,
        color: "red",
        shape: "square",
        number: 1,
        language: "japanese",
        display: "一",
    },
    {
        id: 8,
        color: "red",
        shape: "square",
        number: 2,
        language: "japanese",
        display: "二",
    },
    {
        id: 9,
        color: "blue",
        shape: "circle",
        number: 1,
        language: "math",
        display: "1",
    },
    {
        id: 10,
        color: "blue",
        shape: "circle",
        number: 2,
        language: "math",
        display: "2",
    },
    {
        id: 11,
        color: "blue",
        shape: "circle",
        number: 1,
        language: "japanese",
        display: "一",
    },
    {
        id: 12,
        color: "blue",
        shape: "circle",
        number: 2,
        language: "japanese",
        display: "二",
    },
    {
        id: 13,
        color: "blue",
        shape: "square",
        number: 1,
        language: "math",
        display: "1",
    },
    {
        id: 14,
        color: "blue",
        shape: "square",
        number: 2,
        language: "math",
        display: "2",
    },
    {
        id: 15,
        color: "blue",
        shape: "square",
        number: 1,
        language: "japanese",
        display: "一",
    },
    {
        id: 16,
        color: "blue",
        shape: "square",
        number: 2,
        language: "japanese",
        display: "二",
    },
]